### PR TITLE
Add trailing commas

### PR DESCRIPTION
**Pull request by jaakkonakaza**
Set the trailingComma in .prettierrc to 'all" and formatted files

### CODE REVIEW

**Review by Hugos68 — APPROVED** [review]
lgtm, thanks!

**Comment by endigo9740** [comment]
@jaakkonakaza @Hugos68 I'd like to be part of the conversation when making sweeping linting changes like this please. I don't actually agree with this change and it may need to be reverted.

**Comment by Hugos68** [comment]
You're right, although I have a pretty opinionated stance on this. Having trailing comma's set to `all` will help a lot when doing peer reviews because it won't cause unneccesary diffs.

**Comment by jaakkonakaza** [comment]
@endigo9740 Sorry about that, I can revert it if we decide to do so!

**Pull request merged**
